name: zxWhitelist
version: '1.0'
main: com.zhuoxin.whitelist.Whitelist
api-version: '1.20'

commands:
  whitelistaddplayer:
    description: add player to whitelist
    aliases: wla
    usage: "/wla <name>"
    permission-message: only OP can use this command
  whitelistdeleteplayer:
    description: delete player form whitelist
    aliases: wld
    usage: "/wld <name>"
    permission-message: only OP can use this command
  whitelistinquire:
    description: inquire all players on the whitelist
    aliases: wli
    usage: "/wli"
    permission-message: only OP can use this command
permissions:
  Whitelist.commands.whitelistaddplayer:
    description: whitelistaddplayer permission
    default: OP
  Whitelist.commands.whitelistdeleteplayer:
    description: whitelistdeleteplayer permission
    default: OP
  Whitelist.commands.whitelistinquire:
    description: whitelistinquire permission
    default: OP